In [24]:
a = "Robert"
b = "Vencedor"
nome_completo = a + " " + b
print(nome_completo)

#print(a[0])
#print(b[0])
#print(a[4])

#print(nome_completo[0:11])

print(nome_completo[7:16].upper())
print(nome_completo.upper())

Robert Vencedor
VENCEDOR
ROBERT VENCEDOR


In [36]:
minha_string = "um rato roeu a roupa do rei de Roma"
print(minha_string)

#metodo .split() transforma a variável em uma lista e exclui o item entre "" da lista
minha_lista = minha_string.split("r")
print(minha_lista)

#metodo .find() encontra caracter em uma variável
busca = minha_string.find("roupa")
print(busca)

#abaixo o metodo find() junto [] conta a quantidade de carcter tendo como inicio o cacter declarado para o inicio da busca
print(minha_string[busca:])

#metodo .replace() troca palavra por outra
minha_string = minha_string.replace("do rei","da rainha")
print(minha_string)

um rato roeu a roupa do rei de Roma
['um ', 'ato ', 'oeu a ', 'oupa do ', 'ei de Roma']
15
roupa do rei de Roma
um rato roeu a roupa da rainha de Roma


In [42]:
#funções
#funções sempre devem estar declaradas na parte de cima do código

def soma (x, y):
    print(x)
    print(y)
    return(x + y)

def multiplicacao(a , b):
    print(a)
    print(b)
    return (a * b)

s = soma (20 , 40)
m = multiplicacao (50 , 10 )
print(soma(s, m))

20
40
50
10
60
500
560


In [59]:
#lendo arquivos
#r somente leitura
#w escrita (caso o arquivo já exista, ele será apagado e um novo arquivo vazio será criado)
#a leitura e escrita (adiciona o novo conteúdo ao fim do arquivo)
#r+ leitura e escrita
#w+ escrita (esse modo assim como o w também apago o conteúdo anterior do arquivo)
#a+ leitura e escrita (abre o arquivo para atuação)

arquivo = open("arquivo.txt")
print(arquivo)

#read line (le apenas as linhas)
linhas = arquivo.readlines()
#print(linhas)

#imprimir linha por linha
for linha in linhas:
    #print(linhas)
    
#imprime tudo
#texto_completo = arquivo.read()
#print(texto_completo)

W = open("arquivo2.txt", "a")


IndentationError: expected an indented block (<ipython-input-59-da3a90b25998>, line 24)

In [79]:
#lista

minha_listafrutas =  ["abacaxi", "melancia", "abacate" ]
minha_listalegumes = ["cenoura",4, "batata", "mandioca"]
minha_listaflores = ["rosa", "cravo", "margarida"]

#lista em branco
minha_lista_4 = []

print(minha_listafrutas[0])

for item in minha_listalegumes:
    print(item)


#comando len retorna o tamanho da lista declarada
tamanho = len(minha_listaflores)
print(tamanho)

#comando append adiciona itens a lista
minha_listafrutas.append("maracuja")

print(minha_listafrutas)

#conferindo se determinado item está na lista
if "cenoura" in minha_listalegumes:
    print("cenoura esta na lista")
    
#comando del remove item da lista ou lista interia
# del minha_litaflores[:] ( apaga tudo)
del minha_listaflores[2:]
print(minha_listaflores)

#ordenando listas

lista_ordenada = [55,66,88,99,100,44,78,56,1000,400]

lista.sort()
print(lista_ordenada)

lista_ordenada.reverse()
print(lista_ordenada)

minha_listafrutas.sort()
print(minha_listafrutas)

abacaxi
cenoura
4
batata
mandioca
3
['abacaxi', 'melancia', 'abacate', 'maracuja']
cenoura esta na lista
['rosa', 'cravo']
[55, 66, 88, 99, 100, 44, 78, 56, 1000, 400]
[400, 1000, 56, 78, 44, 100, 99, 88, 66, 55]
['abacate', 'abacaxi', 'maracuja', 'melancia']


In [91]:
#dicionários

meu_dicionario = {"A":"AMEIXA", "B":"BOLA", "C":"CACHORRO"}
print(meu_dicionario["A"])

for chave in meu_dicionario:
    print(chave)
    print(chave+"-"+meu_dicionario[chave])
    
#usando funções no dicionário

#.items separa por tuplas ( conjunto de dados imutáveis)
for i in meu_dicionario.items():
    print(i)
#.values retorna apenas os valores
for i in meu_dicionario.values():
    print(i)


AMEIXA
A
A-AMEIXA
B
B-BOLA
C
C-CACHORRO
('A', 'AMEIXA')
('B', 'BOLA')
('C', 'CACHORRO')
AMEIXA
BOLA
CACHORRO


In [100]:
#números aleatórios

import random

#.random.randint chama um número aletaório
numero = random.randint(0, 10)
print(numero)

#random.choice seleciona um número de uma lista 
lista_4 = [1,2,3,4]
numero = random.choice(lista_4)
print(numero)


1
2


In [103]:
#tratamento de exceções

r = 2
w = 0

try:
    print(r/w)
    
except:
    print("Não é possivel dividir por zero")

Não é possivel dividir por zero


In [112]:
#lista comprehension

#x = [1, 2, 3, 4, 5]
#y = []

#for i in x:
    #y.append(1**2)

#print(x)
#print(y)

x = [1, 2, 3, 4, 5]
y = [i**2 for i in x]
# não deu certo z = [i for i in x if 1%2==1]

print("usando list comprehension")
print(x)
print(y)
#print(z)




usando list comprehension
[1, 2, 3, 4, 5]
[1, 4, 9, 16, 25]


In [117]:
#função enumerate

lista = [ "abacate", "bola", "cachorro"]

#range cria um vetor e len ver o tamanho
for i in range(len(lista)):
    print(i, lista[i])
    
lista_dois = ["abacate", "bola", "cachorro"] 

for i, nome in enumerate(lista):
    print(i, nome)

0 abacate
1 bola
2 cachorro
0 abacate
1 bola
2 cachorro


In [119]:
#função map

def dobro(x):
    return x*2

valor = [1, 2, 3, 4, 5]

valor_dobrado = map(dobro, valor)

valor_dobrado = list(valor_dobrado)
print(valor_dobrado)

[2, 4, 6, 8, 10]


In [121]:
#função reduce

from functools import reduce #comando para importar função reduce

def soma (x , y):
    return x+y

lista = [1, 3, 7, 8, 90]

soma = reduce(soma, lista)
print(soma)


109


In [129]:
#função zip

lista1 =  [1, 2, 3, 4, 5]
lista2 = ["acabete", "bola", "cachorro", "dinheiro", "elefante"]

for numero, nome in zip(lista1,lista2):
    print(numero, nome)

1 acabete
2 bola
3 cachorro
4 dinheiro
5 elefante


In [136]:
def dpMakeChange(coinValueList,change,minCoins):

   for cents in range(change+1):

      coinCount = cents

      for j in [c for c in coinValueList if c <= cents]:

            if minCoins[cents-j] + 1 < coinCount:

               coinCount = minCoins[cents-j]+1

      minCoins[cents] = coinCount

   return minCoins[change]


def main():

    amnt = 72

    clist = [1,5,10,25,50]

    coinCount = [0]*(amnt+1)

    print(dpMakeChange(clist,amnt,coinCount),"moedas")



main()


5 moedas


In [138]:
100.0 / 2.0 // 3 // 4 / 5.0

0.8

In [142]:
import numpy as np


x = np.arange(2, 11).reshape(3,3)

print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
